Task 4
rudolf101/formal-lang-course pull request #4
Opened 2022-10-05 17:57 UTC by rudolf101

- [x] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать **функцию** достижимости с регулярными ограничениями для нескольких стартовых вершин.
  - Предусмотрите два варианта задачи:
    - Для указанного множества стартовых вершин найти множество достижимых.
    - Для каждой вершины из указанного множества найти множество достижимых вершин.
- [x] На основе реализованной функции реализовать **функцию** выполнения регулярных запросов к графам. Не забыть предоставить возможность задавать стартовые и финальные вершины в графе и вариант решаемой задачи.
  - Для конструирования регулярного запроса и графа использовать результаты [Задачи 2](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task2.md).
- [x] Добавить необходимые тесты.

2022-10-06 08:07 UTC, EgorOrachyov requested changes

2022-10-06 08:07 UTC, EgorOrachyov commented on tests/test_regex_to_dfa.py
> -    )
Не очень понял, а что с этим тестом не так, чем не понравился?

2022-10-06 09:30 UTC, rudolf101 commented on tests/test_regex_to_dfa.py
> -    )
Тест периодически падал на CI убунты. Локально ошибка не воспроизводилась. Учитывая, что тест не влияет на покрытие было принято решение его удалить.

2022-10-06 16:04 UTC, rudolf101 commented on tests/test_regex_to_dfa.py
> -    )
Вроде удалось выяснить из-за чего падал тест, вернул его с пометкой. Возможно в дальнейшем разберусь, что идет не так на убунте.

2022-10-07 10:59 UTC, EgorOrachyov approved these changes

2022-10-07 11:01 UTC, merged