Task-5
rudolf101/formal-lang-course pull request #5
Opened 2022-10-19 20:59 UTC by rudolf101

- [ ] Используя [pyCuBool](https://pypi.org/project/pycubool/) или [pygraphblas](https://github.com/Graphegon/pygraphblas) реализовать алгоритм для указанных выше трёх задач (аналогично предыдущим домашним работам).
- [ ] Подключить решение из предыдущей работы.
- [ ] Сформировать набор данных.
  - [ ] Выбрать некоторые графы из [набора](https://jetbrains-research.github.io/CFPQ_Data/dataset/index.html). Не забудьте обосновать, почему выбрали именно эти графы.
  - [ ] Используя функцию из первой домашней работы узнать метки рёбер графов и на основе этой информации сформулировать не менее четырёх различных запросов к каждому графу. Лучше использовать наиболее часто встречающиеся метки. Требования к запросам:
      - Запросы ко всем графам должны следовать некоторому общему шаблону. Например, если есть графы ```g1``` и ```g2``` с различными наборами меток, то ожидается, что запросы к ним будут выглядеть, например, так:
        - ```g1```:
          - ```(l1 | l2)* l3```
          - ```(l3 | l4)+ l1*```
          - ```l1 l2 l3 (l4|l1)*```
        - ```g2```:
          - ```(m1 | m3)* m2```
          - ```(m1 | m3)+ m2*```
          - ```m1 m2 m3 (m3|m1)*```
      - В запросах должны использоваться все общепринятые конструкции регулярных выражений  (замыкание, конкатенация, альтернатива). То есть хотя бы в одном запросе к каждому графу должна быть каждая из этих конструкций.
  - [ ] Для генерации множеств стартовых вершин воспользоваться [этой функцией](https://jetbrains-research.github.io/CFPQ_Data/reference/graphs/generated/cfpq_data.graphs.utils.multiple_source_utils.html#cfpq_data.graphs.utils.multiple_source_utils.generate_multiple_source). Не забывайте, что от того, как именно устроено стартовое множество, сильно зависит время вычисления запроса.
- [ ] Сформулировать этапы эксперимента. Что нужно сделать, чтобы ответить на поставленные вопросы? Почему?
- [ ] Провести необходимые эксперименты, замеры
- [ ] Оформить результаты экспериментов
- [ ] Провести анализ результатов
  - [ ] Ответить на поставленные вопросы
  - [ ] Аргументировать ответы (пользуясь полученными результатами экспериментов)
- [ ] Не забыть опубликовать notebook

2022-10-19 21:23 UTC, rudolf101 commented
Приветствую! Пришлось знатно покопаться в своем коде. Провел большую чистку, исправил недочеты, как, например, с периодически падающими тестами на линуксе. Рефакторинг немного коснулся ключевой функциональности, в этих местах были добавлены новые тесты. В целом, проведена большая работа над ошибками.

Прошу прощения, что все файлы сжаты в один коммит, скорее не влазил по времени, по возможности исправлю в будущем. Также прошу заметить, что ключевые файлы задания после дедлайна не изменялись. Последний коммит, затрагивающий пересборку notebook был сделан из-за несохранившейся отрисовки графиков, чтобы исключить необходимость собирать файл заново вручную. Большое спасибо за понимание.

2022-10-27 08:45 UTC, EgorOrachyov requested changes
1. Библиотека pycubool предполагает использование GPU, поэтому в описание обородования хорошо бы включить описание и характеристики ГПУ.
2. А вы точно включили в настройках использование Nvidia GPU? Тк судя по временам, либо алгоритмы реализованы плохо, либо pycubool использовал fall-back cpu бэкенд.
3. В описании результатов хорошо было бы не только констатировать что бы стрее и во сколько раз, но и дать какое-то инженерное объяснение -- почему так происходит
4. В каком-то из выводов фигурировала фраза что ускорение scipy pycubool не зависит от размера графа, но зависит от regex только. Звучит очень противоречиво, т.к. в том году как раз было вижно, что tensor based алгорим на бОльших графах бОльшее ускорение давал.
5. Реализация bfs based алгоритма имеет нюанс -- постоянный read-back данных с ГПУ на ЦПУ, это может быть одной из причин слабой разницы по скорости
6. Логи слишком большие, мешаю чтению отчета, лучше их сократить
7. Не хватает в финале секции `Заключение` с общими выводами
8. В конце графики и комментаирии сильно разбросаны, не очень ясно, какой график к чему относиться. Я бы сделал имена графиков более детальными (алгоримт какой, какая реализация scipy/pycubool) сгруппировал теснее

2022-10-29 20:07 UTC, rudolf101 commented
Исправлены замечания
* Эксперимент был перенесен на другое железо
* Добавлен раздел с общим заключением
* Сгруппированы графики с описанием
* Убраны ненужные логи

2022-10-31 08:13 UTC, EgorOrachyov approved these changes

2022-11-02 19:38 UTC, merged