Task 6
rudolf101/formal-lang-course pull request #6
Opened 2022-10-23 18:21 UTC by rudolf101

- [x] Используя [возможности pyformlang для работы с контекстно-свободными грамматиками](https://pyformlang.readthedocs.io/en/latest/modules/context_free_grammar.html) реализовать **функцию** преобразования контекстно-свободной грамматики в ослабленную нормальную форму Хомского (ОНФХ), но не классическую нормальную форму Хомского (НФХ). НФХ является частным случаем ОНФХ, а значит можно утверждать, что грамматика, находящаяся в НФХ находится и в ОНФХ. Но в данной задаче нас интересует максимально слабая форма, то есть ОНФХ, но не НФХ.
- [x] Предусмотреть возможность чтения грамматики из файла. Формат файла определяется возможностями pyformalng. Например, можно использовать [эту функцию](https://pyformlang.readthedocs.io/en/latest/modules/context_free_grammar.html#pyformlang.cfg.CFG.from_text).
- [x] Добавить необходимые тесты.

2022-10-23 18:23 UTC, rudolf101 commented
За основу была взята ветка #5, так как тот PR еще не попал в мейн, из-за этого некоторые коммиты из 5-го задания попали и сюда.

2022-10-29 20:20 UTC, rudolf101 commented
Перенес изменения из 5й ветки, чтобы избавиться от потенциальных проблем с мерджем в мастер.

2022-11-02 19:28 UTC, EgorOrachyov requested changes
Сделайте что-то с файлами, которые не относятся к ревью. смотреть на 14 файлов желания нет

2022-11-02 19:29 UTC, rudolf101 commented
Хорошо, пока в голове пару вариантов созрело, щас что-нибудь придумаю.

2022-11-02 20:15 UTC, rudolf101 commented
@EgorOrachyov сделал новый PR, там проблема исправлена. После мерджа этого PR сразу исправлю 7ю домашку.

2022-11-02 20:15 UTC, closed without merging